version: '3.5'

services:
  db:
    image: 308605260180.dkr.ecr.us-east-2.amazonaws.com/postgres:13.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: Bookworm

  bookworm:
    image: bookworm
    restart: always
    ports:
      - "9990:9990"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "9990"

networks:
  default:
    name: bookworm-local-dev