version: '3.1'

services:

  db:
    image: 308605260180.dkr.ecr.us-east-2.amazonaws.com/postgres:13.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: Bookworm
