CREATE SCHEMA BOOKWORM;

CREATE TABLE IF NOT EXISTS BOOKWORM.BOOK(
    bookId UUID PRIMARY KEY,
    id SERIAL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    isbn TEXT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    minPrice INTEGER NOT NULL,
    maxPrice INTEGER NOT NULL,
    genreId UUID NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL
);