CREATE TABLE IF NOT EXISTS BOOKWORM.GENRE(genreId UUID PRIMARY KEY, genreName TEXT NOT NULL UNIQUE);

ALTER TABLE BOOKWORM.BOOK ADD COLUMN genreId UUID;

ALTER TABLE BOOKWORM.BOOK ADD CONSTRAINT fk_genreId FOREIGN KEY (genreId) REFERENCES BOOKWORM.GENRE(genreId);