ALTER TABLE BOOKWORM.BOOK ADD COLUMN createdAt timestamp;

ALTER TABLE BOOKWORM.BOOK ADD COLUMN updatedAt timestamp;

ALTER TABLE BOOKWORM.AUTHOR ADD COLUMN createdAt timestamp;

ALTER TABLE BOOKWORM.AUTHOR ADD COLUMN updatedAt timestamp;